#!/usr/bin/python3

import datetime as dt
import dateutil.parser as dp
#import feedgen.util as fu
import locale
import sys
#import time as tm

def formatRFC2822(date):
    '''Make sure the locale setting do not interfere with the time format.
    '''
    old = locale.setlocale(locale.LC_ALL)
    locale.setlocale(locale.LC_ALL, 'C')
    date = date.strftime('%a, %d %b %Y %H:%M:%S %z')
    locale.setlocale(locale.LC_ALL, old)
    return date

def make_canonical_datetime(date):
    canon = dt.datetime.fromtimestamp(dp.parse(date).timestamp(),
                                      tz=dt.timezone.utc)
    return formatRFC2822(canon)

def main():
    for a in sys.argv[1:]:
        print(make_canonical_datetime(a))

if __name__ == "__main__":
    main()
